version: '3.3'
services:
    db:
        image: mysql:5.7
        restart: always
        container_name: kareoke_db
        environment:
            MYSQL_ROOT_PASSWORD: 'kareoke_db'
            COMPOSE_CONVERT_WINDOWS_PATHS: 1
        ports:
            - '3307:3306'
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/scripts:/docker-entrypoint-initdb.d
    playlist_server:
        build: .
        restart: always
        container_name: playlist
        depends_on:
        - db
